// Use DBML to define your database structure
// Docs: https://dbml.dbdiagram.io/docs

Table Benchmarks {
  id integer [pk, increment]
  title varchar[256]
  vendor text
  release int 
  version int
  release_date date
}

Table Test {
  id int [pk, increment]
}

