
on: [push]

jobs:
  test_action:
    runs-on: ubuntu-latest
    name: Test inpec-profile-update action
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v3
      # Update profile
      - name: Updates profile
        uses: mitre/inspec-profile-update-action@main
        # Set env variables
        env:
          profile: 094e2264-9f8b-4a5f-9f29-ab47138436fb
      # Create new branch
      - name: Push changes to new PR
        uses: peter-evans/create-pull-request@v4
        with:
          branch: update-profile
          delete-branch: true